version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - url-shortener
    networks:
      - url-shortener-network
    restart: unless-stopped

  psql:
    image: postgres:17-alpine
    container_name: psql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: url_shortener
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - url-shortener-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d url_shortener"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - url-shortener-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  url-shortener:
    build:
      context: ../
      dockerfile: Dockerfile.dev
    container_name: url-shortener
    expose:
      - "8080"
    ports: # Remote debugging
      - "5005:5005"
    volumes:
      - ../src:/app/src
      - ../build:/app/build
      - gradle-cache:/home/gradle/.gradle
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
      # Database
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql:5432/url_shortener
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_LOCATIONS=classpath:db/migration
      # Redis
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      psql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - url-shortener-network

networks:
  url-shortener-network:
    driver: bridge

volumes:
  postgres-data:
  gradle-cache:
